language: java
addons:
  sonarcloud:
    organization: "nbaars-github"
    token:
      secure: "jH85e/nRqmie7A7/JFy2j94RF85gzO4gZ7hEnYnj2tlxROOYNY8FEF/baWX/jFImvRkgWjurHte+w1ncaZn353vzq6v8kV1w8vO4xJWHQwBywQIkobGEVShEuZ7qneheEjcRN3uMt2ACj4iC7jOFxsFJ7EPUks10Tdfdh0VxDv4Zvy1IRC5VlJE/dt3TgzEmz4rjyhXYY+ava90OGUs2pfaA5jCk0sISGNCILCnuaEnhhyyGBnyYYpZ6tbyUBkEpMgY6CkITeaollY6llmH8/K/axn5W9mjHngycsf6dDAFWQCWmC5MimONtbS295n9kzoG/DaUmn0lEdvX4keRXKHZtgGOjwGz2lEdRlGzEctCOTykE4MTID67P4tBc9MNuhMUSBv5kqgNj5JpdlJLtI2TlsdOEmT7uJoZ0iLiKOCeWkbvQRtAUGOWXj0x2xmH3lTH3aL9gyp/F3SBLmaJ2gp26iTEYzeHMrq/twGLbFIFkuYr97yUB02BWlZRubng2fkori+80UJP1fhTVa4csLl7LphelM/AE6q56v99QVxpCdAMyPN44iJIGYxnyXcKAc3rW7Y5la0PEpCx2s96sYf/FE8Sr4H9iVcd0QuTPt2RIoaCnD26v+Z4q92ZBJCdOW42zPsEAhaXIkhxyXbc4Ep1KV1vVRt0sUC73Puq76Tk="
jdk:
- oraclejdk8
install:
- "./travis-install-libsodium.sh"
- "/bin/true"
- export LD_LIBRARY_PATH=$HOME/libsodium/lib:$LD_LIBRARY_PATH
script:
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- if [ ! -z "${TRAVIS_TAG}" ]; then ./gradlew -DbuildNumber=${TRAVIS_TAG} clean build; else ./gradlew clean build; fi
- sonar-scanner
cache:
  directories:
  - "$HOME/.gradle"
deploy:
  provider: releases
  api_key:
    secure: SfpFUq0aJ3vYICs0FO7tKCwVTNffXSnwx2dMDs3diVwHuOtj1yl0lWk++NxkXzq6KGPzN9oj2Zmx0GBdOWs8vyCm1xdTWtswocFhnPlqmgR44fAJ1IS7AOs6jdTqr9UHccm1dSFMjz+8KYLHbfcgj+LYYrz6uAig4Lsk6n8z7pzop8U/pzcPnFDviTk3WJ/soTiRg5j1LYaqPVvR7ezS1U2YdQiCDidoWjvAn8H0QhyaCnw61JoSAXxO8nMrDVDJhuJT7rFtNBgNBLeXSVx35wWXadqWzmqBrn9boT79L0MJ+YbClsBhWFcV2ojwCcZhb3h9jaLKWxgdBRqyXbpRISs3pI1xoFNeaK+fqnD03ZvKlHBpSw2WEnSiJiev1WtrZMV4lL3PsJtILpu9K9VUttP9jFQDE0ZUoynpUnOhpFij8Hh4K86UzLTL/86fKDvIQUNzw/52uemaVYEOMZGhvTcC5RVPMBcAQHOjW0mKOzYqG5Dv3weQ0spDFY8gNM4B7h+GR80wAZdMyx3/YF+ZZ27hWIWN4QtJMJICrN8Mm9/iVlfav77ocSsQDelLlcTzxe0229XcRpdNC5M/Q+71CZGC4f4uIpyPg7XGoodeca4qFuJ/tU3zGlaVeM115fljwDjs/vbI4Qs7JUPgh3uscayxBUBG/4rEzrPlL1e6sZM=
  file: "*/build/libs/*.jar"
  on:
    repo: nbaars/paseto4j
    tags: true


